wcコマンドの課題提出
hirano-vm4/ruby-practices pull request #11
Opened 2022-11-27 08:46 UTC by hirano-vm4

いつもお世話になっております！

wcコマンドの課題を提出します😄
お手数をおかけしますが、確認をお願いいたします！

2022-12-03 17:10 UTC, u1tnk requested changes
ロジックは良さそうですが、変数の命名でいくつか気になるのでコメント確認ください 🙏

2022-12-03 17:10 UTC, u1tnk commented on 06.wc/mywc.rb
> +    Hash['', contents]
ここは `{"" => contents}`方がrubyとしては一般的な書き方になります。
業務では同じ処理なら一般的な方が同僚に伝わりやすいのでなるべくよく見る書き方にするように心がけてください。

2022-12-03 17:10 UTC, u1tnk commented on 06.wc/mywc.rb
> +    Hash[ARGV.zip(contents)]
こちらも `ARGV.zip(contents).to_h` の方がよく見る形式と思います。

2022-12-03 17:10 UTC, u1tnk commented on 06.wc/mywc.rb
> +  formatted_element.each do |filename, content|
rubyでは複数形だと基本的に配列(hashの場合もたまにあります)を表す慣習があるので複数形の elementsにしましょう。
後で elementsも使ってるようなので合わせて欲しいというのもあります。

2022-12-03 17:10 UTC, u1tnk commented on 06.wc/mywc.rb
> +  formatted_element = read_file_contents
contentsとementsの使いわけはどのように考えてますでしょうか？

`read_file_contents`というメソッドで取得したものは複数あったりしなければ `file_contents`であることが自然と思います。

2022-12-04 02:57 UTC, hirano-vm4 commented on 06.wc/mywc.rb
> +    Hash['', contents]
@u1tnk さん

確認ありがとうございます🙇‍♂️

`Hash['', contents]`よりも`{"" => contents}`のほうが一般的なのですね！勉強になりました😄

2022-12-04 03:00 UTC, hirano-vm4 commented on 06.wc/mywc.rb
> +    Hash[ARGV.zip(contents)]
@u1tnk さん
`Hash[ARGV.zip(contents)]`よりも` ARGV.zip(contents).to_h`のほうが一般的。メモして修正しました🙇‍♂️

2022-12-04 03:02 UTC, hirano-vm4 commented on 06.wc/mywc.rb
> +  formatted_element.each do |filename, content|
@u1tnk さん
こちらも修正しました✨配列、ハッシュは慣習として複数形にする！メモしました！

2022-12-04 03:06 UTC, hirano-vm4 commented on 06.wc/mywc.rb
> +  formatted_element = read_file_contents
@u1tnk さん
contentsとementsの使いわけ統一するという意識でいなかったかもしれません💦あまりいろいろなところに同じ名付けをするとよくないかな？というくらいの意識だったので、なるべく同じものを使って繋がりがわかる記述に修正していきたいと思います！


ここも修正しました！

2022-12-04 03:10 UTC, hirano-vm4 commented
@u1tnk さん

アドバイスいただいた内容を踏まえ、修正を行いました。

>contentsとementsの使いわけはどのように考えてますでしょうか？
read_file_contentsというメソッドで取得したものは複数あったりしなければ file_contentsであることが自然と思います。

この部分だけ反映を忘れ、2回コミットいれていますが確認いただければ助かります🙇‍♂️

2022-12-04 16:31 UTC, u1tnk approved these changes

2022-12-05 10:44 UTC, merged