【課題提出】カレンダーのプログラム(ruby)
hirano-vm4/ruby-practices pull request #2
Opened 2022-08-31 14:19 UTC by hirano-vm4

カレンダーのプログラム(ruby)の課題を作成しました。確認のほど、よろしくお願いします🔥

2022-09-05 01:56 UTC, func09 requested changes
コメントしましたー。
引数の順番を変えると例外になってしまうケースがあるので、それを修正してみてください。

2022-09-05 01:56 UTC, func09 commented on 01.fizzbuzz/fizzbuzz.rb
> +(1..20).each do |print|
今回の提出とは関係ないFizzBuzzのコードが入ってしまっていますね。
プルリクエストの差分に入らないように解消できますか？

2022-09-05 01:56 UTC, func09 commented on 02.calendar/mycal
> +month = ARGV[0] || today.month
```
% ./mycal -y 2000 -m 1
./mycal:22:in `initialize': invalid date (Date::Error)
	from ./mycal:22:in `new'
	from ./mycal:22:in `<main>'
```

引数の順番を変えるとエラーになってしまいますね。

2022-09-05 01:56 UTC, func09 commented on 02.calendar/mycal
> +puts header.center(20)
👍

2022-09-05 13:10 UTC, hirano-vm4 commented on 01.fizzbuzz/fizzbuzz.rb
> +(1..20).each do |print|
@func09 さん
いつもありがとうございます！合っているか自信がありませんが、Revertして消しました。確認をお願いいたします！

2022-09-05 13:12 UTC, hirano-vm4 commented on 02.calendar/mycal
> +month = ARGV[0] || today.month
@func09 さん
ご助言いただきありがとうございます🙇‍♂️

ARGV.getopts を使うことでオプションの順番関係なく使えるように変更しました。あらためてご確認のほど、よろしくお願いいたします🔥

2022-09-05 13:47 UTC, hirano-vm4 commented on 02.calendar/mycal
> +puts header.center(20)
ありがとうございます🔥

2022-09-06 02:52 UTC, func09 commented on 02.calendar/mycal
> +year = params[:y] || today.year
引数に m や y を指定しても今月のカレンダーになってしまうようでした。
確認お願いしますー

2022-09-06 03:10 UTC, func09 commented on 01.fizzbuzz/fizzbuzz.rb
> +(1..20).each do |print|
@hirano-vm4 

revert するとコミットが消えてしまうのでおかしくなってしまうかも...

* git pull --rebase origin main（コンフリクトするので解消する）
* git add 01.fizzbuzz/fizzbuzz.rb
* git push -f origin my-cal

こんな感じで試してみてもらえますか？

もしこれで解消しなかったら、main から新しくブランチを切り直して再度プルリクを出してもらう形でもOKです〜 🙏

2022-09-12 06:59 UTC, merged